obstacle_range: 1.0
raytrace_range: 1.5
footprintL: [[-28.75, -31.25],[-28.75, -31.25],[0,0]]
inflation_radius: 0.1
map_topic: /map
subscribe_to_update: true
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: rgbd_cam_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true