global_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.5
  static_map: true
  rolling_window: false
  width: 10
  height: 10
  origin_x: 0
  origin_y: 0
  resolution: 0.05
  inflation_radius: 0.6