global_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.5
  static_map: true
  rolling_window: true
  width: 3
  height: 3
  origin_x: 10
  origin_y: -10
  resolution: 0.05
  inflation_radius: 0.6